const fullItems = [
    {url: "img/full_items/abyssal_blade.jpg", name: "Abyssal Blade"},
    {url: "img/full_items/aeon_disk.jpg", name: "Aeon Disk"},
    {url: "img/full_items/aghanims_scepter.jpg", name: "Aghanim's Scepter"},
    {url: "img/full_items/arcane_blink.jpg", name: "Arcane Blink"},
    {url: "img/full_items/armlet_of_mordiggian.jpg", name: "Armlet of Mordiggian"},
    {url: "img/full_items/assault_cuirass.jpg", name: "Assault Cuirass"},
    {url: "img/full_items/battlefury.jpg", name: "Battlefury"},
    {url: "img/full_items/blade_mail.jpg", name: "Blade Mail"},
    {url: "img/full_items/bloodstone.jpg", name: "Bloodstone"},
    {url: "img/full_items/bloodthorn.jpg", name: "Bloodthorn"},
    {url: "img/full_items/boots_of_bearing.jpg", name: "Boots of Bearing"},
    {url: "img/full_items/boots_of_travel_2.jpg", name: "Boots of Travel 2"},
    {url: "img/full_items/bracer.jpg", name: "Bracer"},
    {url: "img/full_items/butterfly.jpg", name: "Butterfly"},
    {url: "img/full_items/crimson_guard.jpg", name: "Crimson Guard"},
    {url: "img/full_items/daedalus.jpg", name: "Daedalus"},
    {url: "img/full_items/dagon.jpg", name: "Dagon"},
    {url: "img/full_items/desolator.jpg", name: "Desolator"},
    {url: "img/full_items/disperser.jpg", name: "Disperser"},
    {url: "img/full_items/divine_rapier.jpg", name: "Divine Rapier"},
    {url: "img/full_items/eternal_shroud.jpg", name: "Eternal Shroud"},
    {url: "img/full_items/ethereal_blade.jpg", name: "Ethereal Blade"},
    {url: "img/full_items/eye_of_skadi.jpg", name: "Eye of Skadi"},
    {url: "img/full_items/falcon_blade.jpg", name: "Falcon Blade"},
    {url: "img/full_items/gleipnir.jpg", name: "Gleipnir"},
    {url: "img/full_items/glimmer_cape.jpg", name: "Glimmer Cape"},
    {url: "img/full_items/guardian_greaves.jpg", name: "Guardian Greaves"},
    {url: "img/full_items/hand_of_midas.jpg", name: "Hand of Midas"},
    {url: "img/full_items/harpoon.jpg", name: "Harpoon"},
    {url: "img/full_items/heart_of_tarrasque.jpg", name: "Heart of Tarrasque"},
    {url: "img/full_items/heavens_halberd.jpg", name: "Heaven's Halberd"},
    {url: "img/full_items/helm_of_the_overlord.jpg", name: "Helm of the Overlord"},
    {url: "img/full_items/holy_locket.jpg", name: "Holy Locket"},
    {url: "img/full_items/hurricane_pike.jpg", name: "Hurricane Pike"},
    {url: "img/full_items/kaya_and_sange.jpg", name: "Kaya and Sange"},
    {url: "img/full_items/khanda.jpg", name: "Khanda"},
    {url: "img/full_items/linkens_sphere.jpg", name: "Linken's Sphere"},
    {url: "img/full_items/lotus_orb.jpg", name: "Lotus Orb"},
    {url: "img/full_items/mage_slayer.jpg", name: "Mage Slayer"},
    {url: "img/full_items/magic_wand.jpg", name: "Magic Wand"},
    {url: "img/full_items/manta_style.jpg", name: "Manta Style"},
    {url: "img/full_items/mask_of_madness.jpg", name: "Mask of Madness"},
    {url: "img/full_items/meteor_hammer.jpg", name: "Meteor Hammer"},
    {url: "img/full_items/mjollnir.jpg", name: "Mjollnir"},
    {url: "img/full_items/monkey_king_bar.jpg", name: "Monkey King Bar"},
    {url: "img/full_items/moon_shard.jpg", name: "Moon Shard"},
    {url: "img/full_items/null_talisman.jpg", name: "Null Talisman"},
    {url: "img/full_items/nullifier.jpg", name: "Nullifier"},
    {url: "img/full_items/observer_and_sentry_wards.jpg", name: "Observer and Sentry Ward"},
    {url: "img/full_items/octarine_core.jpg", name: "Octarine Core"},
    {url: "img/full_items/orb_of_corrosion.jpg", name: "Orb of Corrosion"},
    {url: "img/full_items/overwhelming_blink.jpg", name: "Overwhelming Blink"},
    {url: "img/full_items/parasma.jpg", name: "Parasma"},
    {url: "img/full_items/phase_boots.jpg", name: "Phase Boots"},
    {url: "img/full_items/pipe_of_insight.jpg", name: "Pipe of Insight"},
    {url: "img/full_items/power_treads.jpg", name: "Power Treads"},
    {url: "img/full_items/radiance.jpg", name: "Radiance"},
    {url: "img/full_items/refresher_orb.jpg", name: "Refresher Orb"},
    {url: "img/full_items/revenants_brooch.jpg", name: "Revenant's Brooch"},
    {url: "img/full_items/sange_and_yasha.jpg", name: "Sange and Yasha"},
    {url: "img/full_items/satanic.jpg", name: "Satanic"},
    {url: "img/full_items/scythe_of_vyse.jpg", name: "Scythe of Vyse"},
    {url: "img/full_items/shivas_guard.jpg", name: "Shiva's Guard"},
    {url: "img/full_items/silver_edge.jpg", name: "Silver Edge"},
    {url: "img/full_items/solar_crest.jpg", name: "Solar Crest"},
    {url: "img/full_items/soul_ring.jpg", name: "Soul Ring"},
    {url: "img/full_items/spirit_vessel.jpg", name: "Spirit Vessel"},
    {url: "img/full_items/swift_blink.jpg", name: "Swift Blink"},
    {url: "img/full_items/vladmirs_offering.jpg", name: "Vladmir's Offering"},
    {url: "img/full_items/wind_waker.jpg", name: "Wind Waker"},
    {url: "img/full_items/wraith_band.jpg", name: "Wraith Band"},
    {url: "img/full_items/yasha_and_kaya.jpg", name: "Yasha and Kaya"}
];

  

const midItems = [
    {url: "img/mid_items/aether_lens.jpg", name: "Aether Lens"},
    {url: "img/mid_items/arcane_boots.jpg", name: "Arcane Boots"},
    {url: "img/mid_items/boots_of_travel.jpg", name: "Boots of Travel"},
    {url: "img/mid_items/crystalys.jpg", name: "Crystalys"},
    {url: "img/mid_items/diffusal_blade.jpg", name: "Diffusal Blade"},
    {url: "img/mid_items/dragon_lance.jpg", name: "Dragon Lance"},
    {url: "img/mid_items/drum_of_endurance.jpg", name: "Drum of Endurance"},
    {url: "img/mid_items/echo_sabre.jpg", name: "Echo Sabre"},
    {url: "img/mid_items/euls_scepter_of_divinity.jpg", name: "Eul's Scepter of Divinity"},
    {url: "img/mid_items/force_staff.jpg", name: "Force Staff"},
    {url: "img/mid_items/headdress.jpg", name: "Headdress"},
    {url: "img/mid_items/helm_of_the_dominator.jpg", name: "Helm of the Dominator"},
    {url: "img/mid_items/kaya.jpg", name: "Kaya"},
    {url: "img/mid_items/maelstrom.jpg", name: "Maelstrom"},
    {url: "img/mid_items/mekansm.jpg", name: "Mekansm"},
    {url: "img/mid_items/oblivion_staff.jpg", name: "Oblivion Staff"},
    {url: "img/mid_items/orchid_malevolence.jpg", name: "Orchid Malevolence"},
    {url: "img/mid_items/pavise.jpg", name: "Pavise"},
    {url: "img/mid_items/perseverance.jpg", name: "Perseverance"},
    {url: "img/mid_items/phylactery.jpg", name: "Phylactery"},
    {url: "img/mid_items/ring_of_basilius.jpg", name: "Ring of Basilius"},
    {url: "img/mid_items/rod_of_atos.jpg", name: "Rod of Atos"},
    {url: "img/mid_items/sange.jpg", name: "Sange"},
    {url: "img/mid_items/shadow_blade.jpg", name: "Shadow Blade"},
    {url: "img/mid_items/skull_basher.jpg", name: "Skull Basher"},
    {url: "img/mid_items/soul_booster.jpg", name: "Soul Booster"},
    {url: "img/mid_items/tranquil_boots.jpg", name: "Tranquil Boots"},
    {url: "img/mid_items/urn_of_shadows.jpg", name: "Urn of Shadows"},
    {url: "img/mid_items/vanguard.jpg", name: "Vanguard"},
    {url: "img/mid_items/veil_of_discord.jpg", name: "Veil of Discord"},
    {url: "img/mid_items/witch_blade.jpg", name: "Witch Blade"},
    {url: "img/mid_items/yasha.jpg", name: "Yasha"},
]

const sostavlyaushie = [
    {url: "img/sostavlyaushie/band_of_elvenskin.jpg", name: "Band of Elvenskin"},
    {url: "img/sostavlyaushie/cloak.jpg", name: "Cloak"},
    {url: "img/sostavlyaushie/belt_of_strength.jpg", name: "Belt of Strength"},
    {url: "img/sostavlyaushie/blade_of_alacrity.jpg", name: "Blade of Alacrity"},
    {url: "img/sostavlyaushie/blades_of_attack.jpg", name: "Blades of Attack"},
    {url: "img/sostavlyaushie/blight_stone.jpg", name: "Blight Stone"},
    {url: "img/sostavlyaushie/blink_dagger.jpg", name: "Blink Dagger"},
    {url: "img/sostavlyaushie/blitz_knuckles.jpg", name: "Blitz Knuckles"},
    {url: "img/sostavlyaushie/boots_of_speed.jpg", name: "Boots of Speed"},
    {url: "img/sostavlyaushie/broadsword.jpg", name: "Broadsword"},
    {url: "img/sostavlyaushie/chainmail.jpg", name: "Chainmail"},
    {url: "img/sostavlyaushie/circlet.jpg", name: "Circlet"},
    {url: "img/sostavlyaushie/claymore.jpg", name: "Claymore"},
    {url: "img/sostavlyaushie/cornucopia.jpg", name: "Cornucopia"},
    {url: "img/sostavlyaushie/crown.jpg", name: "Crown"},
    {url: "img/sostavlyaushie/demon_edge.jpg", name: "Demon Edge"},
    {url: "img/sostavlyaushie/diadem.jpg", name: "Diadem"},
    {url: "img/sostavlyaushie/eaglesong.jpg", name: "Eaglesong"},
    {url: "img/sostavlyaushie/energy_booster.jpg", name: "Energy Booster"},
    {url: "img/sostavlyaushie/fluffy_hat.jpg", name: "Fluffy Hat"},
    {url: "img/sostavlyaushie/gauntlets_of_strength.jpg", name: "Gauntlets of Strength"},
    {url: "img/sostavlyaushie/ghost_scepter.jpg", name: "Ghost Scepter"},
    {url: "img/sostavlyaushie/gloves_of_haste.jpg", name: "Gloves of Haste"},
    {url: "img/sostavlyaushie/helm_of_iron_will.jpg", name: "Helm of Iron Will"},
    {url: "img/sostavlyaushie/hyperstone.jpg", name: "Hyperstone"},
    {url: "img/sostavlyaushie/iron_branch.jpg", name: "Iron Branch"},
    {url: "img/sostavlyaushie/javelin.jpg", name: "Javelin"},
    {url: "img/sostavlyaushie/magic_stick.jpg", name: "Magic Stick"},
    {url: "img/sostavlyaushie/mantle_of_intelligence.jpg", name: "Mantle of Intelligence"},
    {url: "img/sostavlyaushie/mithril_hammer.jpg", name: "Mithril Hammer"},
    {url: "img/sostavlyaushie/morbid_mask.jpg", name: "Morbid Mask"},
    {url: "img/sostavlyaushie/mystic_staff.jpg", name: "Mystic Staff"},
    {url: "img/sostavlyaushie/observer_ward.jpg", name: "Observer Ward"},
    {url: "img/sostavlyaushie/ogre_axe.jpg", name: "Ogre Axe"},
    {url: "img/sostavlyaushie/orb_of_venom.jpg", name: "Orb of Venom"},
    {url: "img/sostavlyaushie/platemail.jpg", name: "Platemail"},
    {url: "img/sostavlyaushie/point_booster.jpg", name: "Point Booster"},
    {url: "img/sostavlyaushie/quelling_blade.jpg", name: "Quelling Blade"},
    {url: "img/sostavlyaushie/reaver.jpg", name: "Reaver"},
    {url: "img/sostavlyaushie/recipe.jpg", name: "Recipe"},
    {url: "img/sostavlyaushie/ring_of_health.jpg", name: "Ring of Health"},
    {url: "img/sostavlyaushie/ring_of_protection.jpg", name: "Ring of Protection"},
    {url: "img/sostavlyaushie/ring_of_regen.jpg", name: "Ring of Regen"},
    {url: "img/sostavlyaushie/ring_of_tarrasque.jpg", name: "Ring of Tarrasque"},
    {url: "img/sostavlyaushie/robe_of_the_magi.jpg", name: "Robe of the Magi"},
    {url: "img/sostavlyaushie/sacred_relic.jpg", name: "Sacred Relic"},
    {url: "img/sostavlyaushie/sages_mask.jpg", name: "Sages Mask"},
    {url: "img/sostavlyaushie/sentry_ward.jpg", name: "Sentry Ward"},
    {url: "img/sostavlyaushie/shadow_amulet.jpg", name: "Shadow Amulet"},
    {url: "img/sostavlyaushie/slippers_of_agility.jpg", name: "Slippers of Agility"},
    {url: "img/sostavlyaushie/staff_of_wizardry.jpg", name: "Staff of Wizardry"},
    {url: "img/sostavlyaushie/talisman_of_evasion.jpg", name: "Talisman of Evasion"},
    {url: "img/sostavlyaushie/tiara_of_selemene.jpg", name: "Tiara of Selemene"},
    {url: "img/sostavlyaushie/ultimate_orb.jpg", name: "Ultimate Orb"},
    {url: "img/sostavlyaushie/vitality_booster.jpg", name: "Vitality Booster"},
    {url: "img/sostavlyaushie/void_stone.jpg", name: "Void Stone"},
    {url: "img/sostavlyaushie/voodoo_mask.jpg", name: "Voodoo Mask"},
    {url: "img/sostavlyaushie/wind_lace.jpg", name: "Wind Lace"},
]

const recipes = {
    "Abyssal Blade": ["Skull Basher", "Vanguard", "Recipe"],
    "Aeon Disk": ["Vitality Booster", "Energy Booster" ,"Recipe"],
    "Aghanim's Scepter": ["Staff of Wizardry", "Blade of Alacrity", "Ogre Axe", "Point Booster"],
    "Arcane Blink": ["Blink Dagger", "Mystic Staff" ,"Recipe"],
    "Armlet of Mordiggian": ["Helm of Iron Will", "Gloves of Haste", "Blades of Attack", "Recipe"],
    "Assault Cuirass": ["Platemail", "Buckler", "Hyperstone", "Recipe"],
    "Battlefury": ["Quelling Blade", "Claymore", "Cornucopia", "Broadsword", "Recipe"],
    "Blade Mail": ["Broadsword", "Chainmail", "Recipe"],
    "Bloodstone": ["Voodoo Mask", "Soul Booster", "Void Stone"],
    "Bloodthorn": ["Orchid Malevolence", "Hyperstone", "Javelin", "Recipe"],
    "Boots of Bearing": ["Drum of Endurance", "Tranquil Boots", "Recipe"],
    "Boots of Travel 2": ["Boots of Travel", "Recipe"],
    "Bracer": ["Circlet", "Gauntlets of Strength", "Recipe"],
    "Butterfly": ["Eaglesong", "Talisman of Evasion", "Claymore"],
    "Crimson Guard": ["Helm of Iron Will", "Vanguard", "Recipe"],
    "Daedalus": ["Crystalys", "Demon Edge", "Recipe"],
    "Dagon": ["Voodoo Mask", "Diadem", "Recipe"],
    "Desolator": ["Mithril Hammer", "Mithril Hammer", "Blight Stone"],
    "Disperser": ["Diffusal Blade", "Eaglesong", "Recipe"],
    "Divine Rapier": ["Sacred Relic", "Demon Edge"],
    "Eternal Shroud": ["Cloak", "Ogre Axe", "Vitality Booster", "Recipe"],
    "Ethereal Blade": ["Aether Lens", "Ghost Scepter", "Recipe"],
    "Eye of Skadi": ["Ultimate Orb", "Point Booster", "Recipe"],
    "Falcon Blade": ["Fluffy Hat", "Blades of Attack", "Sages Mask", "Recipe"],
    "Gleipnir": ["Maelstrom", "Rod of Atos", "Recipe"],
    "Glimmer Cape": ["Cloak", "Shadow Amulet", "Recipe"],
    "Guardian Greaves": ["Mekansm", "Arcane Boots", "Recipe"],
    "Hand of Midas": ["Gloves of Haste", "Recipe"],
    "Harpoon": ["Echo Sabre", "Diadem", "Recipe"],
    "Heart of Tarrasque": ["Reaver", "Vitality Booster", "Recipe"],
    "Heaven's Halberd": ["Talisman of Evasion", "Sange", "Recipe"],
    "Helm of the Overlord": ["Helm of the Dominator", "Ultimate Orb", "Recipe"],
    "Holy Locket": ["Magic Wand", "", "Diadem", "Recipe"],
    "Hurricane Pike": ["Force Staff", "Dragon Lance", "Recipe"],
    "Kaya and Sange": ["Kaya", "Sange"],
    "Khanda": ["Phylactery", "Crystalys", "Recipe"],
    "Linken's Sphere": ["Ultimate Orb", "Perseverance", "Recipe"],
    "Lotus Orb": ["Platemail", "Perseverance", "Energy Booster", "Recipe"],
    "Mage Slayer": ["Cloak", "Oblivion Staff", "Recipe"],
    "Magic Wand": ["Magic Stick", "Iron Branch", "Iron Branch", "Recipe"],
    "Manta Style": ["Yasha", "Diadem", "Recipe"],
    "Mask of Madness": ["Morbid Mask", "Broadsword"],
    "Meteor Hammer": ["Kaya", "Crown", "Recipe"],
    "Mjollnir": ["Maelstrom", "Hyperstone", "Recipe"],
    "Monkey King Bar": ["Demon Edge", "Blitz Knuckles", "Javelin", "Recipe"],
    "Moon Shard": ["Hyperstone", "Hyperstone"],
    "Null Talisman": ["Circlet", "Mantle of Intelligence", "Recipe"],
    "Nullifier": ["Sacred Relic", "Helm of Iron Will"],
    "Observer and Sentry Ward": ["Observer Ward", "Sentry Ward"],
    "Octarine Core": ["Soul Booster", "Tiara of Selemene"],
    "Orb of Corrosion": ["Gloves of Haste", "Orb of Venom", "Ring of Protection"],
    "Overwhelming Blink": ["Blink Dagger", "Reaver", "Recipe"],
    "Parasma": ["Witch Blade", "Mystic Staff", "Recipe"],
    "Phase Boots": ["Boots of Speed", "Chainmail", "Blades of Attack"],
    "Pipe of Insight": ["Cloak", "Headdress", "Ring of Tarrasque", "Recipe"],
    "Power Treads": {
        required : ["Boots of Speed", "Gloves of Haste", ],
        alternatives: ["Band of Elvenskin", "Belt of Strength", "Robe of the Magi"]
    },
    "Radiance": ["Sacred Relic", "Talisman of Evasion"],
    "Refresher Orb": ["Tiara of Selemene", "Heart of Tarrasque", "Cornucopia", "Recipe"],
    "Revenant's Brooch": ["Sacred Relic", "Voodoo Mask", "Recipe"],
    "Sange and Yasha": ["Sange", "Yasha"],
    "Satanic": ["Reaver", "Morbid Mask", "Claymore"],
    "Scythe of Vyse": ["Mystic Staff", "Tiara of Selemene", "Recipe"],
    "Shiva's Guard": ["Platemail", "Veil of Discord", "Recipe"],
    "Silver Edge": ["Shadow Blade", "Demon Edge", "Recipe"],
    "Solar Crest": ["Pavise", "Crown", "Wind Lace", "Recipe"],
    "Soul Ring": ["Gauntlets of Strength", "Gauntlets of Strength", "Ring of Protection", "Recipe"],
    "Spirit Vessel": ["Urn of Shadows", "Vitality Booster", "Recipe"],
    "Swift Blink": ["Blink Dagger", "Eaglesong", "Recipe"],
    "Vladmir's Offering": ["Morbid Mask", "Buckler", "Ring of Basilius", "Blades of Attack"],
    "Wind Waker": ["Eul's Scepter of Divinity", "Mystic Staff", "Recipe"],
    "Wraith Band": ["Circlet", "Slippers of Agility", "Recipe"],
    "Yasha and Kaya": ["Yasha", "Kaya"],
    
    // midItems
    "Aether Lens": ["Energy Booster", "Void Stone", "Recipe"],
    "Arcane Boots": ["Boots of Speed", "Ring of Basilius", "Recipe"],
    "Boots of Travel": ["Boots of Speed", "Recipe"],
    "Crystalys": ["Claymore", "Blades of Attack", "Recipe"],
    "Diffusal Blade": ["Blade of Alacrity", "Robe of the Magi", "Recipe"],
    "Dragon Lance": ["Blade of Alacrity", "Belt of Strength", "Recipe"],
    "Drum of Endurance": ["Robe of the Magi", "Belt of Strength", "Wind Lace", "Recipe"],
    "Echo Sabre": ["Ogre Axe", "Broadsword", "Void Stone"],
    "Eul's Scepter of Divinity": ["Staff of Wizardry", "Void Stone", "Wind Lace", "Recipe"],
    "Force Staff": ["Staff of Wizardry", "Fluffy Hat", "Recipe"],
    "Headdress": ["Ring of Regen", "Recipe"],
    "Helm of the Dominator": ["Helm of Iron Will", "Diadem", "Recipe"],
    "Kaya": ["Staff of Wizardry", "Robe of the Magi", "Recipe"],
    "Maelstrom": ["Gloves of Haste", "Mithril Hammer", "Javelin"],
    "Mekansm": ["Headdress", "Chainmail", "Recipe"],
    "Oblivion Staff": ["Blitz Knuckles", "Robe of the Magi", "Sages Mask"],
    "Orchid Malevolence": ["Oblivion Staff", "Cornucopia", "Recipe"],
    "Pavise": ["Energy Booster", "Ring of Protection", "Fluffy Hat", "Recipe"],
    "Perseverance": ["Ring of Health", "Void Stone"],
    "Phylactery": ["Diadem", "Point Booster", "Recipe"],
    "Ring of Basilius": ["Sages Mask", "Recipe"],
    "Rod of Atos": ["Staff of Wizardry", "Vitality Booster", "Recipe"],
    "Sange": ["Ogre Axe", "Belt of Strength", "Recipe"],
    "Shadow Blade": ["Shadow Amulet", "Blitz Knuckles", "Broadsword"],
    "Skull Basher": ["Mithril Hammer", "Belt of Strength", "Recipe"],
    "Soul Booster": ["Point Booster", "Energy Booster", "Vitality Booster"],
    "Tranquil Boots": ["Boots of Speed", "Wind Lace", "Ring of Regen"],
    "Urn of Shadows": ["Sages Mask", "Fluffy Hat", "Ring of Protection", "Recipe"],
    "Vanguard": ["Ring of Health", "Vitality Booster"],
    "Veil of Discord": ["Helm of Iron Will", "Crown", "Recipe"],
    "Witch Blade": ["Oblivion Staff", "Chainmail", "Recipe"],
    "Yasha": ["Blade of Alacrity", "Band of Elvenskin", "Recipe"],
};
